db-uri = "postgres://authenticator@127.0.0.1:54330/sixtoc_local"
db-schemas = "public"
db-anon-role = "anon"
jwt-secret = "local-only-secret-for-6toc-e2e-testing-000000"
server-host = "127.0.0.1"
server-port = 54401
